### ISSUE TITLE
Self video preview frame blank after re-join meeting 

### ISSUE THREAD

**Issue by InformamuseSRL** [bluejeans/android-client-sdk#2]
@pavankumarvvijapur @pgodha @pmathew92 
We noticed that the SDK (v.1.6.0) sometimes doesn't show the self video preview if you leave and re-enter the meeting (in a separated activity).
This happens especially after using the incoming content share feature during a call.

The video fragment remains black even if the camera is triggered and local video is transmitted correctly to remote participants.

**Comment by pavankumarvvijapur** [comment]
Thank you for reporting this issue @InformamuseSRL. We are looking into this, we will revert back with more details soon.

**Comment by pmathew92** [comment]
Hi   @InformamuseSRL,
We  tried reproducing the issue you reported on our end and unable to do so.
This is what we tried following your above comment,
    1) Enter meeting join details in Activity A  with a user self video 
    2) Join the actual meeting in Activity B  with the user self video,
    3) start receiving content share from other remote end point
    4) end the meeting and join back

Please confirm the above steps or else what are you doing differently, 
Also could you please answer the following queries:
  
 1) Since there are 2 activities involved, does both the activities contain the self view fragment? If yes then does             the self view fragment gets blacked out in both the activities?

 2) What's the frequency of the issue?

 3) Are you seeing any error messages in the logcat?
 
We have an api to upload the sdk logs? Could you please upload the same and let us know

**Comment by pmathew92** [comment]
Hi @InformamuseSRL ,
Did you had a chance to check the queries that we have asked ?

**Comment by pmathew92** [comment]
Closing this issue for now as it has been inactive for quite some time. Feel free to reopen this or reach out to us if you encounter this issue again

**Comment by pmathew92** [comment]
Closing this issue for now as it has been inactive for quite some time. Feel free to reopen this or reach out to us if you encounter this issue again
